[versions]
autoValue = "1.7.4"
autoValueAnnotations = "1.8"
awsSdk = "2.17.102"
# Used by NcmlEditor. Abandoned, no updates since 2013. https://sourceforge.net/projects/bounce/
# https://sourceforge.net/p/bounce/svn/HEAD/tree/src/main/java/org/bounce/
bounce = "0.18"
commonsIo = "2.5"
groovyAll = "2.5.12"
grpc = "1.42.1"
guava = "31.0.1-jre"
jcommander = "1.81"
jdom2 = "2.0.6"
jfreechart = "1.0.19"
# http://www.jgoodies.com/. Latest version is 1.9.0, but there is breakage when we try to upgrade.
jgoodies = "1.6.0"
jj2000 = "5.4"
jna = "5.10.0"
jsoup = "1.14.3"
jsr305 = "3.0.2"
junit = "4.13.2"
lgooddatepicker = "10.3.1"
logback = "1.2.9"
mockito = "2.28.2"
protobuf = "3.19.2"
re2j = "1.6"
slf4j = "1.7.32"
spock = "1.3-groovy-2.5"
tomcatAnnotationsApi = "6.0.53"
truth = "1.1"

###################
# plugin versions #
###################

execforkPlugin = "0.1.15"
jekyllPlugin = "0.0.5"
nexusPlugin = "0.0.1"
owaspDepCheckPlugin = "6.5.1"
protobufPlugin = "0.8.18"
shadowPlugin = "7.1.2"
spotlessPlugin = "6.1.0"

[libraries]
# cdm-core, uibase, gcdm
autoValue = { group = "com.google.auto.value", name = "auto-value", version.ref = "autoValue" }

# cdm-core, uibase, gcdm
autoValueAnnotations = { group = "com.google.auto.value", name = "auto-value-annotations", version.ref = "autoValueAnnotations" }

awsSdkBom = { group = "software.amazon.awssdk", name = "bom", version.ref = "awsSdk" }
# cdm-s3, cdm-test (test)
awsS3Sdk =  { group = "software.amazon.awssdk", name = "s3" }
# cdm-s3
awsApacheClient =  { group = "software.amazon.awssdk", name = "apache-client" }

# uicdm
bounce = { group = "org.bounce", name = "bounce", version.ref = "bounce" }

grpcBom = { group = "io.grpc", name = "grpc-bom", version.ref = "grpc" }
# gcdm
grpcProtobuf = { group = "io.grpc", name = "grpc-protobuf" }
# gcdm
grpcStub =  { group = "io.grpc", name = "grpc-stub" }
# gcdm
grpcNettyShaded = { group = "io.grpc", name = "grpc-netty-shaded" }

# cdm-core, bufr, grib, cdm-s3, uibase, uicdm, gcdm
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

# command line parsing
# cdm-core, bufr, grib
jcommander = { group = "com.beust", name = "jcommander", version.ref = "jcommander" }

# cdm-core, bufr, grib, cdm-test (test), uibase, uicdm
jdom2 = { group = "org.jdom", name = "jdom2", version.ref = "jdom2" }

# uicdm
jfreechart = { group = "org.jfree", name = "jfreechart", version.ref = "jfreechart" }

# uibase, uicdm
jgoodies = { group = "com.jgoodies", name = "jgoodies-forms", version.ref = "jgoodies" }

# grib
jj2000 = { group = "edu.ucar", name = "jj2000", version.ref = "jj2000" }

# netcdf4
jna = { group = "net.java.dev.jna", name = "jna", version.ref = "jna" }

# Annotations: Nullable
# udunits, cdm-core, bufr, grib, netcdf4, cdm-s3, uibase
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }

# uicdm
lgooddatepicker = { group = "com.github.lgooddatepicker", name = "LGoodDatePicker", version.ref = "lgooddatepicker" }

# control protobuf artifact versions using the protobuf-bom
# see also netcdf-java-platform/build.gradle.kts
protobufBom = { group = "com.google.protobuf", name = "protobuf-bom", version.ref = "protobuf" }
# cdm-core, bufr, grib, netcdf4 (test), uicdm, gcdm
protobufJava = { group = "com.google.protobuf", name = "protobuf-java" }

# cdm-core, bufr, grib, cdm-test (test), uicdm
re2j = { group = "com.google.re2j", name = "re2j", version.ref = "re2j" }

# udunits (test), cdm-core, bufr, grib, netcdf4, cdm-s3, cdm-test (test), uibase, uicdm, gcdm, docs
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

# gcdm
slf4jJdk14 = { group = "org.slf4j", name = "slf4j-jdk14", version.ref = "slf4j" }

# gcdm
tomcatAnnotationsApi = { group = "org.apache.tomcat", name = "annotations-api", version.ref = "tomcatAnnotationsApi" }

##########################
# test only dependencies #
##########################

# cdm-core, cdm-test, gcdm
commonsIo = { group = "commons-io", name = "commons-io", version.ref = "commonsIo" }

# cdm-core, netcdf4
groovyAll = { group = "org.codehaus.groovy", name = "groovy-all", version.ref = "groovyAll" }

# cdm-core, uibase
mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }

# cdm-core, netcdf4
spockCore = { group = "org.spockframework", name = "spock-core", version.ref = "spock" }

# grib
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }

# udunits, cdm-core, bufr, grib, netcdf4, cdm-s3, cdm-test, uibase, uicdm, gcdm
junit = { group = "junit", name = "junit", version.ref = "junit" }

# udunits, cdm-core, bufr, grib, netcdf4, cdm-s3, cdm-test, uibase, gcdm, docs
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }

# cdm-core, grib, cdm-test
truthJava8Extension = { group = "com.google.truth.extensions", name = "truth-java8-extension", version.ref = "truth" }

# udunits, cdm-core, bufr, grib, netcdf4, cdm-s3, cdm-test, docs
logbackClassic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

[plugins]
# gcdm
execforkPlugin = { id = "com.github.psxpaul.execfork", version.ref = "execforkPlugin" }
# docs
jekyllPlugin = { id = "edu.ucar.unidata.site.jekyll", version.ref = "jekyllPlugin"}
# docs, uicdm
nexusPlugin = { id = "edu.ucar.unidata.nexus", version.ref = "nexusPlugin"}
# all but docs
owaspDepCheckPlugin = { id = "org.owasp.dependencycheck", version.ref = "owaspDepCheckPlugin" }
# bufr, grib, uicdm, gcdm
protobufPlugin = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
# uicdm
shadowPlugin = { id = "com.github.johnrengelman.shadow", version.ref = "shadowPlugin" }
# all
spotlessPlugin = { id = "com.diffplug.spotless", version.ref = "spotlessPlugin" }
