# set the theme
theme: unidata-jekyll-theme

# this will appear in an HTML meta tag, sidebar, and perhaps elsewhere
docset_version: 6.0

# this appears on the top navigation bar next to the home button
topnav_title: netCDF-Java

# this appears in the html browser tab for the site title (seen mostly by search engines, not users)
site_title: netCDF-Java User Guide

# this appears in the footer
site_topic: netCDF-Java User Guide

# if you have google-analytics ID, put it in. if not, edit this value to blank.
# e.g. google_analytics: UA-92978945-1
google_analytics: UA-92978945-1

# the preview server used. Leave as is.
host: 127.0.0.1

# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.
port: 4005

# these are the files and directories that jekyll will exclude from the build
#exclude:
#  - Gemfile.lock


# used as a contact email and subject line for the Feedback link in the top navigation bar
feedback_email: support-netcdf-java@unidata.ucar.edu
feedback_subject_line: Documentation Feedback

# if you uncomment the next line, the Feedback link gets removed
# feedback_disable: true

# if you uncomment the next line, it changes the Feedback text
# feedback_text: "Need help?"

# if you uncomment the next line, it changes where the feedback link points to
# feedback_link: "http://helpy.io/"

# library used for syntax highlighting
highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true
collections:
  tooltips:
    output: false

# these are defaults used for the frontmatter for these file types
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      sidebar: userguide_sidebar

sidebars:
  - userguide_sidebar

# project logo (32x32), name, main landing page  (currently used in the footer)
project_logo: https://www.unidata.ucar.edu/images/logos/thredds_netcdf-32x32.png
project_name: netCDF-Java
project_landing_page: https://unidata.ucar.edu/software/netcdf-java/

# needed for sitemap.xml files
# must include trailing slash, leave off the version :-)
base_docs_url: https://docs.unidata.ucar.edu/netcdf-java/

# if more than one docset, also need to supply the name of the docset here to be used
# in the sitemap.xml files.
docset_name: userguide
