on: [pull_request]

jobs:
  tests-zulu:
    name: netCDF-Java Tests (Zulu JDK)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest 8, 11 LTS versions
        java: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - name: Install netCDF-C
        run: sudo apt update && sudo apt-get install libnetcdf-dev
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and test with Gradle
        run: ./gradlew --info --stacktrace testAll
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: netCDF-Java_JUnit_Results_${{ github.sha }}_Zulu-JDK-${{ matrix.java }}
          path: build/reports/allTests

  tests-adpotopenjdk-hs:
    name: netCDF-Java Tests (AdoptiumJDK-HS)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest Adoptium LTS releases, and latest non-LTS version supported by gradle
        java: [ 8, 11, 14 ]
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest Adoptium JDK ${{ matrix.java }} (hotspot) built for linux
        run: curl -L "https://api.adoptopenjdk.net/v3/binary/latest/${{ matrix.java }}/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk" -o aojdk${{ matrix.java }}-hs.tar.gz
      - name: Setup Latest Adoptium JDK (hotspot) ${{ matrix.java }}
        uses: actions/setup-java@master
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
          jdkFile: ./aojdk${{ matrix.java }}-hs.tar.gz
      - name: Print java version
        run: java -version
      - name: Install netCDF-C
        run: sudo apt update && sudo apt-get install libnetcdf-dev
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-${{ matrix.java }}-gradle
      - name: Build and test with Gradle
        run: ./gradlew --info --stacktrace testAll
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: netCDF-Java_JUnit_Results_${{ github.sha }}Adoptium-HS-${{ matrix.java }}
          path: build/reports/allTests

  check-assemble-adpotopenjdk-hs:
    name: Check fresh assemble of netCDF-Java project (AdoptiumJDK-HS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest Adoptium JDK (hotspot) built for linux
        run: curl -L "https://api.adoptopenjdk.net/v3/binary/latest/11/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk" -o aojdk11-hs.tar.gz
      - name: Setup Latest Adoptium JDK (hotspot)
        uses: actions/setup-java@master
        with:
          java-version: 11
          architecture: x64
          jdkFile: ./aojdk11-hs.tar.gz
      - name: Print java version
        run: java -version
      - name: Build with Gradle
        run: ./gradlew assemble --refresh-dependencies

  spotless:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Code Style Check with Gradle and Spotless
        run: ./gradlew clean spotlessCheck
